sudo: false

language: rust

rust:
  # - nightly
  - beta
  - stable

env:
  global:
    # secure:

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo --only stable doc

after_success:
  - |
      travis-cargo --only stable doc-upload --branch stable
